# Generated by Django 2.0.2 on 2018-06-09 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=450)),
                ('name', models.CharField(default='', max_length=50)),
                ('semester', models.CharField(default='', max_length=50)),
                ('room_number', models.CharField(default='', max_length=50)),
                ('year', models.CharField(default='', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='Department Description', max_length=450)),
                ('name', models.CharField(default='Department Name', max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, max_length=350)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('school_id', models.IntegerField(default=0)),
                ('is_student', models.BooleanField(default=False, verbose_name='Student')),
                ('is_teacher', models.BooleanField(default=False, verbose_name='Teacher')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school_app.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('description', models.CharField(default='', max_length=450)),
                ('weekly_agenda', models.CharField(default='Agenda Goes Here', max_length=450)),
                ('last_modifield', models.DateTimeField(auto_now_add=True)),
                ('monday_date', models.DateField(blank=True, null=True)),
                ('tuesday_date', models.DateField(blank=True, null=True)),
                ('wednesday_date', models.DateField(blank=True, null=True)),
                ('thursday_date', models.DateField(blank=True, null=True)),
                ('friday_date', models.DateField(blank=True, null=True)),
                ('monday_plan', models.CharField(default='a', max_length=400)),
                ('tuesday_plan', models.CharField(default='s', max_length=400)),
                ('wednesday_plan', models.CharField(default='d', max_length=400)),
                ('thursday_plan', models.CharField(default='f', max_length=400)),
                ('friday_plan', models.CharField(default='g', max_length=400)),
                ('weekend_plan', models.CharField(default='h', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school_app.Profile')),
                ('teaches3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaches3', to='school_app.Subject')),
                ('teaches4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaches4', to='school_app.Subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school_app.Teacher'),
        ),
        migrations.AddField(
            model_name='department',
            name='student',
            field=models.ManyToManyField(blank=True, to='school_app.Student'),
        ),
        migrations.AddField(
            model_name='department',
            name='subject',
            field=models.ManyToManyField(blank=True, to='school_app.Subject'),
        ),
        migrations.AddField(
            model_name='department',
            name='teacher',
            field=models.ManyToManyField(blank=True, to='school_app.Teacher'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='student',
            field=models.ManyToManyField(blank=True, to='school_app.Student'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school_app.Subject'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school_app.Teacher'),
        ),
    ]
