# Generated by Django 2.0.2 on 2018-06-04 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Algebra_101',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=450)),
                ('weekly_agenda', models.CharField(default='', max_length=450)),
                ('last_modifield', models.DateTimeField(auto_now_add=True)),
                ('monday_date', models.DateField(blank=True, null=True)),
                ('monday_plan', models.CharField(default='a', max_length=300)),
                ('tuesday_plan', models.CharField(default='s', max_length=300)),
                ('wednesday_Plan', models.CharField(default='d', max_length=300)),
                ('thursday_plan', models.CharField(default='f', max_length=300)),
                ('friday_plan', models.CharField(default='g', max_length=300)),
                ('weekend_plan', models.CharField(default='h', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Biology_101',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_date', models.CharField(max_length=300)),
                ('tuesday_date', models.CharField(max_length=300)),
                ('wednesday_date', models.CharField(max_length=300)),
                ('thursday_date', models.CharField(max_length=300)),
                ('friday_date', models.CharField(max_length=300)),
                ('monday_plan', models.CharField(max_length=300)),
                ('tuesday_plan', models.CharField(max_length=300)),
                ('wednesday_Plan', models.CharField(max_length=300)),
                ('thursday_plan', models.CharField(max_length=300)),
                ('friday_plan', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Custom_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=450)),
                ('weekly_agenda', models.CharField(default='', max_length=450)),
                ('last_modifield', models.DateTimeField(auto_now_add=True)),
                ('monday_date', models.DateField(default=None)),
                ('tuesday_date', models.DateField(default=None)),
                ('wednesday_date', models.DateField(default=None)),
                ('thursday_date', models.DateField(default=None)),
                ('friday_date', models.DateField(default=None)),
                ('monday_plan', models.CharField(default='a', max_length=300)),
                ('tuesday_plan', models.CharField(default='s', max_length=300)),
                ('wednesday_Plan', models.CharField(default='d', max_length=300)),
                ('thursday_plan', models.CharField(default='f', max_length=300)),
                ('friday_plan', models.CharField(default='g', max_length=300)),
                ('weekend_plan', models.CharField(default='h', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='History_101',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_agenda', models.CharField(max_length=450)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, max_length=350)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('school_id', models.IntegerField(default=0)),
                ('is_student', models.BooleanField(default=False, verbose_name='Student')),
                ('is_teacher', models.BooleanField(default=False, verbose_name='Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('class1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class1', to='school_app.Algebra_101')),
                ('class2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class2', to='school_app.Biology_101')),
                ('student_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school_app.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('teacher_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school_app.Profile')),
                ('teaches1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaches1', to='school_app.Algebra_101')),
                ('teaches2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaches2', to='school_app.Biology_101')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='history_101',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school_app.Teacher'),
        ),
        migrations.AddField(
            model_name='custom_class',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school_app.Teacher'),
        ),
        migrations.AddField(
            model_name='algebra_101',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school_app.Teacher'),
        ),
    ]
