# Generated by Django 2.0.2 on 2018-06-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='name',
        ),
        migrations.AddField(
            model_name='classroom',
            name='description',
            field=models.CharField(default='TBA', max_length=300),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='room_number',
            field=models.CharField(default='TBA', max_length=10),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='time',
            field=models.CharField(blank=True, default='TBA', max_length=10, null=True),
        ),
    ]
