# Generated by Django 2.0.2 on 2018-06-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='time',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
