# Generated by Django 2.0.2 on 2018-08-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_auto_20180810_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='semester',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='classroom',
            name='year',
            field=models.CharField(default='', max_length=4),
        ),
    ]
