# Generated by Django 2.0.2 on 2018-08-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_auto_20180810_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
