# Generated by Django 2.0.2 on 2018-06-23 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_auto_20180622_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_plan',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_app.Course'),
        ),
        migrations.AlterField(
            model_name='lesson_plan',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_app.Teacher'),
        ),
    ]
