# Generated by Django 2.0.2 on 2018-06-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_auto_20180623_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_plan',
            name='week_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
