# Generated by Django 2.0.2 on 2018-06-25 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0005_lesson_plan_week_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson_plan',
            old_name='weekly_agenda',
            new_name='agenda',
        ),
    ]
