# Generated by Django 2.0.2 on 2018-07-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0007_auto_20180707_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school_id',
            field=models.IntegerField(blank=True, default=0, max_length=15, null=True),
        ),
    ]
