# Generated by Django 2.0.2 on 2018-07-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0009_auto_20180709_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='school_id',
            field=models.CharField(blank=True, default=0, max_length=15, null=True),
        ),
    ]
