# Generated by Django 2.0.2 on 2018-07-20 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0013_auto_20180719_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson_plan',
            old_name='friday_plan',
            new_name='friday_assignment',
        ),
        migrations.RenameField(
            model_name='lesson_plan',
            old_name='monday_plan',
            new_name='monday_assignment',
        ),
        migrations.RenameField(
            model_name='lesson_plan',
            old_name='thursday_plan',
            new_name='thursday_assignment',
        ),
        migrations.RenameField(
            model_name='lesson_plan',
            old_name='tuesday_plan',
            new_name='tuesday_assignment',
        ),
        migrations.RenameField(
            model_name='lesson_plan',
            old_name='wednesday_plan',
            new_name='wednesday_assignment',
        ),
        migrations.RenameField(
            model_name='lesson_plan',
            old_name='weekend_plan',
            new_name='weekend_assignment',
        ),
    ]
