# Generated by Django 2.0.2 on 2018-08-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0014_auto_20180720_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
