# Generated by Django 2.0.2 on 2018-04-27 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class1', to='homepage.Subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class2', to='homepage.Subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class4', to='homepage.Subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teaches1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaches1', to='homepage.Subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teaches2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaches2', to='homepage.Subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teaches3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaches3', to='homepage.Subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teaches4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaches4', to='homepage.Subject'),
        ),
    ]
